#!/bin/bash #Author: Kyle Biggins
echo Add Docker Repo.
dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo
echo Install & enable docker plus compose.
dnf install -y docker-ce
systemctl enable --now docker
dnf install -y docker-compose
echo Add user to the docker group.
usermod -aG docker $USER
echo Apply cgroup fix, reboot required.
dnf install -y grubby
grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
echo Install npm, NodeJS, nvm.
dnf install -y nodejs
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
echo Install VSCode.
rpm --import https://packages.microsoft.com/keys/microsoft.asc
sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
dnf check-update
dnf install -y code
echo Install Vagrant.
dnf install -y vagrant
